### PR TITLE
Easy Node Setup CLI

### PR DESCRIPTION
**Pull request by serdarozturk**
make easy-setup

1. create .env with build-config
2. ask tnt address
3. lookup ip address, if not true, write your own public ip address
4. docker up
5. setup completed

no need to edit with vim or nano.

### CODE REVIEW

**Comment by grempe** [comment]
Thanks for this PR. While this provides some good functionality I'd like to see it be a bit more full featured before we merge something like this in.

cc: @filoozom 

Some suggestions:

- It should be written in Javascript if possible.
- It should be a full fledged CLI application that parses and accepts args (see our CLI app for an example)
- It should be able to be compiled to a single executable binary file using the `pkg` command, similar also to the CLI tool.
- The source code for this should reside in a standalone repository.
- It should read the ETH address from something like an `--eth-tnt-addr` arg, which should do validation on that address to ensure that it is a valid address. It should normalize the address to lower case.
- It should read the public URI from something like an `--public-uri` arg, which should do validation to ensure that this arg is composed of a full URI (not just the IP) and that it is a valid URI that can be parsed. If should also ensure that the host portion of the URI is an IPv4 IP address that is routable (no private IPs allowed).
- The previous two args should be combined and written to a `.env` file following the rules for setting the environment variables in that file.
- It should read the HMAC auth key value from the `--auth-key` arg, and if provided it should write a file to the `keys` dir in the form of `ETH-ADDRESS.key` and the value should be the value of this auth key arg. The auth key should be validated to be the proper length and only contain hex values.

Once created, and packaged as a no-dependency binary, this command line tool should be able to be pulled down into another context with a simple wget/curl of a single file.

If either you or @filoozom are interested in continuing on this I'd be happy to setup a new repo for this, or talk through the details of usage and packaging with you.

Thanks!

**Comment by filoozom** [comment]
I'd gladly pick this up if @serdarozturk doesn't want to. Send me the link to the new repo once it's set up. 😉

**Comment by filoozom** [comment]
By the way, here's the repo for the CLI if someone has comments: https://github.com/filoozom/chainpoint-node-cli.

**Comment by jacohend** [comment]
Thanks. We've incorporated this idea into our new init process.

**Pull request closed without merging**
